#!/usr/bin/env bash

# shellcheck disable=SC2155

SILENT='true'
TAG='rewrite'

while [[ $# -gt 0 ]]; do
    case "$1" in
        -s | --silent) readonly SILENT='true' ;;
        -t | --tag)
            if [[ -n "$2" ]] && [[ "$2" != -* ]]; then
                readonly TAG="$2"
                shift
            else
                echo "Option --tag requires an argument"
                exit 1
            fi
            ;;
        --tag=?*)
            readonly TAG="${1#*=}"
            ;;
        *) echo "Invalid argument: $1" && exit 1 ;;
    esac
    shift
done

if [[ "$TAG" != "main" && ! "$TAG" =~ ^v0\.[1-9]\.[0-9]+$ ]]; then
    echo "Tag $TAG does not exist."
    exit 1
fi

if [[ "$SILENT" == "true" ]]; then
    curl -fsSL "https://raw.githubusercontent.com/trimclain/final/$TAG/final" --output final
else
    curl -fL# "https://raw.githubusercontent.com/trimclain/final/$TAG/final" --output final
fi

chmod 755 final
./final
