#!/usr/bin/env bash
#
# Arch Linux Install Script
# My modifications of ChrisTitusTech/linutil
# Credit: https://github.com/ChrisTitusTech/linutil/blob/main/core/tabs/system-setup/arch/server-setup.sh
#
# Author: @trimclain
# License: GPL-3.0

# shellcheck disable=SC2155,SC2164
# Disabled:
# "Declare and assign separately to avoid masking return values":
#  https://www.shellcheck.net/wiki/SC2155
# "Use 'pushd ... || exit' or 'pushd ... || exit' in case pushd fails":
#  https://www.shellcheck.net/wiki/SC2164

curl -fsSL "https://raw.githubusercontent.com/trimclain/final/rewrite/final" --output final
chmod 755 final
