#!/usr/bin/env bash

# shellcheck disable=SC2155

SILENT='false'
TAG='rewrite'

if command -v tput > /dev/null; then
    readonly GREEN=$(tput setaf 2)
    readonly RESET=$(tput sgr0)
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        -s | --silent) readonly SILENT='true' ;;
        -t | --tag)
            if [[ -n "$2" ]] && [[ "$2" != -* ]]; then
                readonly TAG="$2"
                shift
            else
                echo "Option --tag requires an argument"
                exit 1
            fi
            ;;
        --tag=?*)
            readonly TAG="${1#*=}"
            ;;
        *) echo "Invalid argument: $1" && exit 1 ;;
    esac
    shift
done

[[ "$SILENT" == "true" ]] || echo "Installing the final script..."

if [[ "$SILENT" == "true" ]]; then
    curl -fsSL "https://raw.githubusercontent.com/trimclain/final/$TAG/final" --output final
else
    curl -fL# "https://raw.githubusercontent.com/trimclain/final/$TAG/final" --output final
fi

chmod 755 final

[[ "$SILENT" == "true" ]] || echo "${GREEN}Installation finished. Run ./final${RESET}"
